export const ADD_NOTE_REQUEST="ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS="ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILURE="ADD_NOTE_FAILURE";

export const GET_NOTE_REQUEST="GET_NOTE_REQUEST";
export const GET_NOTE_SUCCESS="GET_NOTE_SUCCESS";
export const GET_NOTE_FAILURE="GET_NOTE_FAILURE";

export const UPDATE_NOTE_REQUEST="UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS="UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAILURE="UPDATE_NOTE_FAILURE";

export const DELETE_NOTE_REQUEST="DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS="DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILURE="DELETE_NOTE_FAILURE";


